// Structured per-artist facts for quiz questions and knowledge cards.
// Fields:
//   born     — birthplace + year
//   based    — current/last working location
//   training — school or formative apprenticeship
//   signature— named series, project, or institution they built
//   method   — distinctive material / process clause
//   thesis   — short paraphrase of the artist's argument
//   cohort   — historical scene/movement/peers
//   pron     — { written, ipa, lang } for pronunciation
//   wiki     — Wikipedia slug for summary fetch
//   portrait — URL to a photo of the artist (filled by fetch_portraits)

const QUIZ_FACTS = {

  // ── Painting ──
  a146: { // Lucas Arruda
    born: 'São Paulo, Brazil, 1983',
    based: 'São Paulo, Brazil',
    training: 'Fundação Armando Álvares Penteado (FAAP), São Paulo',
    signature: 'Deserto-Modelo — small atmospheric landscape paintings from memory',
    method: 'Small-format landscape built from memory rather than direct observation',
    thesis: 'Landscape is a verb, an event of perception — not a depicted view',
    cohort: 'Brazilian painterly tradition between modernist abstraction and Romantic landscape',
    pron: { written: 'LOO-kahs ah-ROO-dah', ipa: '/ˈlukɐs ɐˈʁudɐ/', lang: 'pt-BR' },
    wiki: 'Lucas_Arruda_(artist)',
  },
  a176: { // Victor Man
    born: 'Cluj, Romania, 1974',
    based: 'Cluj and Berlin',
    training: 'University of Art and Design Cluj-Napoca',
    signature: 'Dark, slow figurative paintings drawing on Northern Renaissance and Orthodox iconography',
    method: 'Painting filtered through hermetic, art-historical, and erotic symbolism',
    thesis: 'Figuration as a vessel for ambiguity that never fully resolves',
    cohort: 'Cluj School — emerged alongside Adrian Ghenie and Mircea Cantor in early 2000s Romania',
    pron: { written: 'VEEK-tor MAHN', ipa: '/ˈviktor man/', lang: 'ro-RO' },
    wiki: 'Victor_Man',
  },
  a188: { // Yu Nishimura
    born: 'Kanagawa, Japan, 1982',
    based: 'Kanagawa, Japan',
    training: 'Tama Art University, Tokyo',
    signature: 'Veiled figurative paintings pulled from anime backgrounds and Édouard Vuillard',
    method: 'Thin glazes on visible canvas weave producing half-formed, half-receding figures',
    thesis: 'Attention without grasping — a plea for porosity in figurative painting',
    cohort: 'Contemporary Japanese figurative painters (post-Murakami Superflat)',
    pron: { written: 'YOO nee-shee-MOO-rah', ipa: '/jɯ ɲiɕimɯɾa/', lang: 'ja-JP' },
    wiki: 'Yu_Nishimura',
  },
  a206: { // Amy Sillman
    born: 'Detroit, Michigan, 1955',
    based: 'Brooklyn, NY and Berlin',
    training: 'School of Visual Arts, New York',
    signature: 'Editor of zine The O-G; argumentative gestural-abstract painting',
    method: 'Painting through revision and self-argument — colour as emotional and political event',
    thesis: 'Abstraction can hold feeling and politics at once — a yellow can carry uncertainty',
    cohort: 'Post-postmodern revival of gestural painting, New York late-1990s',
    pron: { written: 'AY-mee SILL-muhn', ipa: '/ˈeɪmi ˈsɪlmən/', lang: 'en-US' },
    wiki: 'Amy_Sillman',
  },
  a203: { // Dana Schutz
    born: 'Livonia, Michigan, 1976',
    based: 'Brooklyn, NY',
    training: 'CalArts (BFA) and Columbia University (MFA)',
    signature: 'Frank from Observation series — paintings of the world\'s last man',
    method: 'Narrative painting from invented subjects that could not have been witnessed',
    thesis: 'Painting can host group catastrophe, panic, and gallows comedy without kitsch',
    cohort: 'Early-2000s figurative narrative painting; controversy around Open Casket (Whitney Biennial 2017)',
    pron: { written: 'DAY-nuh SHUTS', ipa: '/ˈdeɪnə ʃʊts/', lang: 'en-US' },
    wiki: 'Dana_Schutz',
  },
  a221: { // Lisa Yuskavage
    born: 'Philadelphia, Pennsylvania, 1962',
    based: 'New York',
    training: 'Tyler School of Art (BFA), Yale (MFA)',
    signature: 'Pin-up-derived nudes mobilizing soft-core figuration and 19th-century pastoral',
    method: 'Eroticized colour painting that courts vulgarity rather than ironizing it',
    thesis: 'The eroticized female body is a serious site for colour, light, and shame',
    cohort: 'Yale figurative cohort with John Currin and Sean Landers',
    pron: { written: 'YOOS-kuh-vidge', ipa: '/ˈjʊskəvɪdʒ/', lang: 'en-US' },
    wiki: 'Lisa_Yuskavage',
  },
  a313: { // Marina Perez Simão
    born: 'Espírito Santo, Brazil, 1980',
    based: 'São Paulo, Brazil',
    training: 'Painter via curatorial path; worked with the Cildo Meireles estate before painting full-time',
    signature: 'Rippling colour-field bands derived from Brazilian modernism — Tarsila, Volpi, Burle Marx',
    method: 'Colour-field landscape abstraction collapsing geometry and sensation',
    thesis: 'Contemporary antropofagia — digesting European abstraction through a tropical vocabulary',
    cohort: 'Contemporary Brazilian abstraction; came to painting from curatorial work',
    pron: { written: 'mah-REE-nuh peh-RESS see-MOWN', ipa: '/maˈɾinɐ peˈɾɛs siˈmɐ̃w/', lang: 'pt-BR' },
    wiki: 'Marina_Perez_Sim%C3%A3o',
  },
  a980: { // Wilhelm Sasnal
    born: 'Tarnów, Poland, 1972',
    based: 'Tarnów and Kraków, Poland',
    training: 'Academy of Fine Arts in Kraków',
    signature: 'Co-founder of the Ładnie Group; paintings sourced from photographs and Holocaust documentation',
    method: 'Flat, deskilled painting from photographic source material',
    thesis: 'Painting as a way of slowing down history — refusing to scroll past',
    cohort: 'Ładnie Group, Poland late 1990s — broke from Polish historical painting toward pop and the everyday',
    pron: { written: 'VIL-helm SAHS-nal', ipa: '/ˈvilxɛlm ˈsasnal/', lang: 'pl-PL' },
    wiki: 'Wilhelm_Sasnal',
  },
  a291: { // Mao Yan
    born: 'Xiangtan, Hunan, China, 1968',
    based: 'Nanjing, China',
    training: 'Central Academy of Fine Arts; teaches at Nanjing University of the Arts',
    signature: 'Decades-long portrait series of his German friend Thomas',
    method: 'Pale, near-monochrome portraiture in which the face barely emerges',
    thesis: 'Portraiture as a slow exposure of presence',
    cohort: 'Post-Cultural Revolution Chinese realist painters; refuses Socialist Realism and 1990s Cynical Realism',
    pron: { written: 'MOW YEN', ipa: '/màu jɛ̌n/', lang: 'zh-CN' },
    wiki: 'Mao_Yan',
  },
  a929: { // Matthew Wong
    born: 'Toronto, Canada, 1984 (d. 2019)',
    based: 'Edmonton and Hong Kong (lifetime)',
    training: 'Self-taught; cultural anthropology degree from University of Michigan',
    signature: 'Dotted, jewel-toned landscapes and interiors after Van Gogh, Shitao, and Bonnard',
    method: 'Solitary landscape painting learned publicly via Facebook conversations with other painters',
    thesis: 'Figurative painting can still be made from solitude rather than market demand',
    cohort: 'Self-taught painters of the social-web 2010s',
    pron: { written: 'MAT-yoo WONG', ipa: '/ˈmæθju wɒŋ/', lang: 'en-CA' },
    wiki: 'Matthew_Wong',
  },
  a996: { // Co Westerik
    born: 'The Hague, Netherlands, 1924 (d. 2018)',
    based: 'The Hague, Netherlands',
    training: 'Royal Academy of Art, The Hague',
    signature: 'Hyper-detailed psychological paintings of hands, bodies, and intimate gestures',
    method: 'Slow, microscopic realism on a small scale',
    thesis: 'Contemplation of skin, contact, and minor gestures at a tempo painting has abandoned',
    cohort: 'Post-war Dutch painter who refused the Cobra moment surrounding him',
    pron: { written: 'koh VES-ter-eek', ipa: '/koː ˈʋɛstərɪk/', lang: 'nl-NL' },
    wiki: 'Co_Westerik',
  },
  a356: { // Etel Adnan
    born: 'Beirut, Lebanon, 1925 (d. 2021)',
    based: 'Sausalito, California and Paris',
    training: 'Sorbonne (philosophy); UC Berkeley; Harvard',
    signature: 'Small palette-knife landscapes of Mount Tamalpais, seen from her California kitchen',
    method: 'Quick, uncorrected palette-knife strokes on small canvases',
    thesis: 'Painting was where she could be silent — colour says what Arabic, French, and English could not',
    cohort: 'Lebanese diaspora; poet before painter; late-discovered after age 80',
    pron: { written: 'EH-tell AD-nahn', ipa: '/ˈɛtɛl ɑdˈnɑn/', lang: 'ar' },
    wiki: 'Etel_Adnan',
  },

  // ── Sculpture ──
  a149: { // Huma Bhabha
    born: 'Karachi, Pakistan, 1962',
    based: 'Poughkeepsie, New York',
    training: 'Rhode Island School of Design (BFA), Columbia University (MFA)',
    signature: 'Totemic figures of cork, styrofoam, clay, and burnt wood',
    method: 'Junkyard assemblage and casting referencing Gandharan Buddha statuary and sci-fi prophecy',
    thesis: 'Figuration can carry catastrophe without illustrating it — a witness left after something unseen',
    cohort: 'Post-9/11 American sculpture; Pakistani diaspora',
    pron: { written: 'HOO-mah BAH-bah', ipa: '/ˈhuma ˈbʱaːbʱaː/', lang: 'ur' },
    wiki: 'Huma_Bhabha',
  },
  a57: { // Carol Bove
    born: 'Geneva, Switzerland, 1971',
    based: 'Red Hook, Brooklyn',
    training: 'New York University',
    signature: 'Collage sculpture — bent steel I-beams reading as ribbons',
    method: 'Steel beams shaped and painted into floppy, monumental abstractions',
    thesis: 'Postwar formal vocabulary is good for something only if treated as malleable, not canonical',
    cohort: 'Early-2000s NY sculpture playing with 1960s sources (Playboy, peacock feathers, Judd)',
    pron: { written: 'KAH-rull boh-VAY', ipa: '/ˈkærəl boʊˈveɪ/', lang: 'en-US' },
    wiki: 'Carol_Bove',
  },
  a213: { // Andra Ursuța
    born: 'Salonta, Romania, 1979',
    based: 'Brooklyn, NY',
    training: 'Columbia University',
    signature: 'Vandal Lust — lead-crystal and glass casts made around the artist\'s own body',
    method: 'Cast lead crystal and glass shaped around her own body',
    thesis: 'Sculpture embodies Eastern European post-Communist abjection without explaining it',
    cohort: 'Post-Communist Eastern European diaspora artists in New York',
    pron: { written: 'AHN-drah oor-SOOT-sah', ipa: '/ˈandra urˈsut͡sa/', lang: 'ro-RO' },
    wiki: 'Andra_Ursu%C8%9Ba',
  },
  a501: { // Adrián Villar Rojas
    born: 'Rosario, Argentina, 1980',
    based: 'Nomadic team-based studio practice',
    training: 'National University of Rosario (visual arts)',
    signature: 'Met rooftop commission The Theater of Disappearance (2017); monumental unfired-clay sculptures',
    method: 'Site-specific monumental sculpture made to crack and decay across the exhibition',
    thesis: 'Geology and extinction as medium — sculpture made for a future viewer\'s absence',
    cohort: 'Contemporary Argentine sculpture; Venice Biennale Argentine Pavilion 2011',
    pron: { written: 'ah-dree-AHN bee-YAR ROH-hahs', ipa: '/aˈðɾjan biˈʎaɾ ˈroxas/', lang: 'es-AR' },
    wiki: 'Adri%C3%A1n_Villar_Rojas',
  },
  a794: { // Berlinde De Bruyckere
    born: 'Ghent, Belgium, 1964',
    based: 'Ghent, Belgium',
    training: 'Sint-Lucas Beeldende Kunst, Ghent',
    signature: 'Wax-on-wax horse hides and human-limb sculptures shown under blankets and in vitrines',
    method: 'Layered wax casting producing forms that read both freshly dead and slowly transforming',
    thesis: 'The wounded body as a contemporary sacred site — neither religious nor secular',
    cohort: 'Contemporary Belgian sculpture; haunted by Catholic boarding-school imagery of suffering',
    pron: { written: 'ber-LIN-duh duh BROYK-uh-ruh', ipa: '/bɛrˈlɪndə də ˈbrœykərə/', lang: 'nl-BE' },
    wiki: 'Berlinde_De_Bruyckere',
  },
  a458: { // Cristina Iglesias
    born: 'San Sebastián, Spain, 1956',
    based: 'Madrid, Spain',
    training: 'Chelsea School of Art, London; studied sculpture under Tony Cragg',
    signature: 'Vegetal bronze screens and water installations carved into public ground',
    method: 'Suspended pavilions, woven bronze foliage, and architectural water work',
    thesis: 'Public sculpture as enterable ambiguous space — not the standing male monument',
    cohort: 'New Spanish sculptural generation of the late 1980s',
    pron: { written: 'krees-TEE-nah ee-GLAY-syas', ipa: '/kɾisˈtina iˈɣlesjas/', lang: 'es-ES' },
    wiki: 'Cristina_Iglesias',
  },
  a963: { // Tau Lewis
    born: 'Toronto, Canada, 1993',
    based: 'Brooklyn, NY',
    training: 'Self-taught',
    signature: 'Quilted leather-and-fur masks and figures she calls ancestors and Black-aquatic scouts',
    method: 'Hand-stitched textile assemblage from family scrap and salvaged material',
    thesis: 'Diaspora as repair — craft and material salvage compose a worldview the gallery did not author',
    cohort: 'Post-2016 self-taught Black diasporic textile sculpture',
    pron: { written: 'TOW LOO-iss', ipa: '/taʊ ˈluːɪs/', lang: 'en-CA' },
    wiki: 'Tau_Lewis',
  },
  a803: { // Eva Jospin
    born: 'Paris, France, 1975',
    based: 'Paris, France',
    training: 'École nationale supérieure des Beaux-Arts, Paris',
    signature: 'Dense cardboard forests and grotto interiors',
    method: 'Layering and cutting cardboard into immersive forest and grotto architecture',
    thesis: 'The romantic European forest is still available for sculpture — if you make it out of trash',
    cohort: 'Contemporary French sculpture; permanent installation at Mobilier National',
    pron: { written: 'EH-vah zhos-PAN', ipa: '/eva ʒɔsˈpɛ̃/', lang: 'fr-FR' },
    wiki: 'Eva_Jospin',
  },
  a853: { // Sanford Biggers
    born: 'Los Angeles, California, 1970',
    based: 'New York',
    training: 'Morehouse College; School of the Art Institute of Chicago (MFA); Skowhegan',
    signature: 'Quilt paintings on antique American quilts (potentially Underground Railroad signals)',
    method: 'Painting and sewing on antique quilts, embedding masks, mandalas, and bullet holes',
    thesis: 'American material history is already a Black history — the artist makes it readable again',
    cohort: 'African-American conceptual sculpture; studied Buddhism in Japan',
    pron: { written: 'SAN-furd BIG-ers', ipa: '/ˈsænfərd ˈbɪɡərz/', lang: 'en-US' },
    wiki: 'Sanford_Biggers',
  },
  a384: { // Klára Hosnedlová
    born: 'Uherské Hradiště, Czech Republic, 1990',
    based: 'Berlin, Germany',
    training: 'UMPRUM (Academy of Arts, Architecture and Design in Prague)',
    signature: 'GROWTH series — silk-thread embroidered panels in sand-and-glass environments',
    method: 'Silk-thread embroidery building tonal gradations line by surgical line',
    thesis: 'Slow textile labour is a contemporary medium, not heritage',
    cohort: 'Contemporary Czech / Eastern European fibre practice',
    pron: { written: 'KLAH-rah HOS-ned-LOH-vah', ipa: '/ˈklaːra ˈɦosnɛdlovaː/', lang: 'cs-CZ' },
    wiki: 'Kl%C3%A1ra_Hosnedlov%C3%A1',
  },

  // ── Photography ──
  a257: { // Hai Bo
    born: 'Changchun, Jilin, China, 1962',
    based: 'Beijing, China',
    training: 'Jilin College of the Arts (painting)',
    signature: 'Re-staged family group portraits decades later — with the absent absent',
    method: 'Photographic diptychs comparing now and then with the same sitters',
    thesis: 'Photography as elegy, not record — its claim on the real is an act of mourning',
    cohort: 'Generation that began painting in the Cultural Revolution; moved to photography in the 1990s',
    pron: { written: 'HIGH BWO', ipa: '/xǎi pwó/', lang: 'zh-CN' },
    wiki: 'Hai_Bo',
  },
  a273: { // Josef Koudelka
    born: 'Boskovice, Moravia, 1938',
    based: 'Paris and Prague (stateless 1970–1987)',
    training: 'Aeronautical engineer by training; self-taught photographer',
    signature: 'Clandestine documentation of the 1968 Soviet invasion of Prague; Gypsies; Exiles',
    method: 'Black-and-white documentary at landscape scale, off-balance composition',
    thesis: 'Documentary photography as geological time — dispossession at landscape scale',
    cohort: 'Magnum Photos cooperative (member since 1971)',
    pron: { written: 'YOH-zef KOH-doot-skah', ipa: '/ˈjozɛf ˈkoʊdɛlka/', lang: 'cs-CZ' },
    wiki: 'Josef_Koudelka',
  },
  a296: { // Richard Misrach
    born: 'Los Angeles, California, 1949',
    based: 'Berkeley, California',
    training: 'UC Berkeley (psychology)',
    signature: 'Desert Cantos — multi-decade large-format colour photography of the American desert',
    method: 'Large-format colour photography of bombing ranges, Salton Sea, Cancer Alley',
    thesis: 'Environmental destruction is a long-running record — beauty is one of the few tools to make people look',
    cohort: 'New Topographics-adjacent American colour photography',
    pron: { written: 'RICH-erd MIZ-rack', ipa: '/ˈrɪtʃərd ˈmɪzræk/', lang: 'en-US' },
    wiki: 'Richard_Misrach',
  },
  a79: { // Roni Horn
    born: 'New York, NY, 1955',
    based: 'New York, NY (with long-term Icelandic projects)',
    training: 'Rhode Island School of Design (BFA), Yale University (MFA)',
    signature: 'Library of Water (Stykkishólmur, Iceland); You Are the Weather; cast-glass sculpture',
    method: 'Cross-medium practice: photography, cast glass, drawing, and text on identity',
    thesis: 'Identity — of a self, a place, a piece of glass — is unstable and mirrored, never closed',
    cohort: 'Post-minimal American sculpture; long-running Iceland engagement',
    pron: { written: 'ROH-nee HORN', ipa: '/ˈroʊni hɔrn/', lang: 'en-US' },
    wiki: 'Roni_Horn',
  },

  // ── Video / Film / Performance ──
  a396: { // Christian Marclay
    born: 'San Rafael, California, 1955',
    based: 'New York and London',
    training: 'Massachusetts College of Art; Cooper Union',
    signature: 'The Clock (2010) — 24-hour montage of film clips matched to real time',
    method: 'Turntablism and film editing as sculptural composition',
    thesis: 'Editing is the contemporary form of composition — cinema\'s fragmentation of time is now everyday attention',
    cohort: 'Early-1980s turntable musicians; Fluxus-adjacent sound art',
    pron: { written: 'KRIS-chen MAR-clay', ipa: '/ˈkrɪstʃən ˈmɑːrkleɪ/', lang: 'en-US' },
    wiki: 'Christian_Marclay',
  },
  a446: { // Tacita Dean
    born: 'Canterbury, UK, 1965',
    based: 'Berlin and Los Angeles',
    training: 'Slade School of Fine Art, UCL',
    signature: 'FILM (2011 Tate Turbine Hall); Disappearance at Sea; Bubble House',
    method: '16mm and 35mm film of landscape, weather, and absence',
    thesis: 'Analog film is a different cognitive technology than digital — a way of attending to time',
    cohort: 'YBA generation; campaigned to keep 16mm/35mm stock in production',
    pron: { written: 'tah-SEE-tah DEEN', ipa: '/təˈsiːtə diːn/', lang: 'en-GB' },
    wiki: 'Tacita_Dean',
  },
  a649: { // Wael Shawky
    born: 'Alexandria, Egypt, 1971',
    based: 'Alexandria, Egypt and Philadelphia',
    training: 'Alexandria University; University of Pennsylvania (MFA)',
    signature: 'Cabaret Crusades trilogy — Crusades narrated by 200-year-old Murano-glass marionettes; founded MASS Alexandria',
    method: 'Feature-length film with marionettes; historical reenactment',
    thesis: 'The historical record is a performance — whose hand and body does the speaking changes the history',
    cohort: 'Contemporary Egyptian/Arab art; Venice Biennale Egyptian Pavilion 2024',
    pron: { written: 'WAY-el SHOW-kee', ipa: '/wæʔil ʃawqiː/', lang: 'ar-EG' },
    wiki: 'Wael_Shawky',
  },
  a490: { // Tino Sehgal
    born: 'London, UK, 1976',
    based: 'Berlin',
    training: 'Studied political economy and dance (Humboldt University and Folkwang Hochschule)',
    signature: 'Constructed situations — choreographed encounters in museums, no documentation permitted',
    method: 'Live performance contracts staged with trained interpreters; no photography, no installation views',
    thesis: 'Immaterial production — speech, encounter, attention — is what art must take seriously as form',
    cohort: 'Contemporary performance / relational aesthetics post-Bourriaud',
    pron: { written: 'TEE-noh SEH-gull', ipa: '/ˈtiːno ˈzeːɡal/', lang: 'de-DE' },
    wiki: 'Tino_Sehgal',
  },
  a583: { // Ryan Trecartin
    born: 'Webster, Texas, 1981',
    based: 'Athens, Ohio (with Lizzie Fitch)',
    training: 'Rhode Island School of Design',
    signature: 'I-Be Area; Re\'Search Wait\'S; Comma Boat — feature-length hyperkinetic videos',
    method: 'Group-performance video in heavy digital makeup; collaborative scripts with Lizzie Fitch',
    thesis: 'The post-2007 social-web subject is a real subject for art',
    cohort: 'Post-internet video (the cohort that named the term)',
    pron: { written: 'TREK-er-tin', ipa: '/ˈtrɛkərtɪn/', lang: 'en-US' },
    wiki: 'Ryan_Trecartin',
  },

  // ── Installation / Conceptual ──
  a414: { // Doris Salcedo
    born: 'Bogotá, Colombia, 1958',
    based: 'Bogotá, Colombia',
    training: 'Universidad de Bogotá Jorge Tadeo Lozano; NYU (MFA)',
    signature: 'Shibboleth (2007 Tate Modern, 167-metre floor crack); Atrabiliarios; concrete-filled furniture',
    method: 'Household furniture and clothing embedded in concrete and hair from civil-violence victims',
    thesis: 'Sculpture\'s first responsibility is to the named, specific, unburied dead',
    cohort: 'Latin American conceptual sculpture; testimony of Colombian civil violence',
    pron: { written: 'DOR-iss sal-SAY-doh', ipa: '/ˈdoɾis salˈseðo/', lang: 'es-CO' },
    wiki: 'Doris_Salcedo',
  },
  a795: { // Leandro Erlich
    born: 'Buenos Aires, Argentina, 1973',
    based: 'Buenos Aires, Argentina',
    training: 'Son of an architect; no formal art school',
    signature: 'Swimming Pool (1999, 21st Century Museum, Kanazawa); Pulled by the Roots; Maison Fond',
    method: 'Architectural perceptual illusions engineered to disorient at building scale',
    thesis: 'A moment of disorientation in the perceptually-saturated urban subject is a political event',
    cohort: 'Surrealism-aligned Argentine sculpture; Argentine Pavilion Venice 2001',
    pron: { written: 'lay-AHN-droh ER-leek', ipa: '/leˈandɾo ˈeɾlit͡ʃ/', lang: 'es-AR' },
    wiki: 'Leandro_Erlich',
  },
  a841: { // Nari Ward
    born: 'St Andrew, Jamaica, 1963',
    based: 'Harlem, New York',
    training: 'City College of New York (BA), Brooklyn College (MFA)',
    signature: 'Amazing Grace (1993); We the People; copper-nail and shoelace installations',
    method: 'Installation from post-industrial diasporic readymades — fire hoses, baby strollers, shopping carts',
    thesis: 'The readymade is not Duchamp\'s joke — it is the assembled archive of who and what a city throws away',
    cohort: 'Early-1990s New York installation; Jamaica/Harlem diasporic readymade',
    pron: { written: 'NAH-ree WORD', ipa: '/ˈnaːri wɔrd/', lang: 'en-JM' },
    wiki: 'Nari_Ward',
  },
  a20: { // Theaster Gates
    born: 'Chicago, Illinois, 1973',
    based: 'Chicago, Illinois',
    training: 'Iowa State University (urban planning, ceramics); Cape Town and Tokoname apprenticeship',
    signature: 'Rebuild Foundation; Dorchester Projects; Stony Island Arts Bank; Johnson Publishing archive',
    method: 'Buys, restores, and reactivates abandoned South Side Chicago buildings as ceramic-and-tar architecture',
    thesis: 'The Black artist\'s most consequential medium in the 21st century is real estate',
    cohort: 'Post-2008 socially engaged sculpture; Chicago South Side',
    pron: { written: 'THEE-as-ter GAYTS', ipa: '/ˈθiːəstər ɡeɪts/', lang: 'en-US' },
    wiki: 'Theaster_Gates',
  },
  a311: { // Adam Pendleton
    born: 'Richmond, Virginia, 1984',
    based: 'New York',
    training: 'Self-directed; Pier Arts Centre fellowship; no MFA',
    signature: 'Black Dada (2008 onward) — concept linking Amiri Baraka\'s poem and Dada\'s anti-syntax',
    method: 'Silkscreen and gesso painting, video portraits, book-objects assembling a Black avant-garde lineage',
    thesis: 'Grammar — typographic, painterly, archival — is itself a place where Black political life takes place',
    cohort: 'Mid-2000s conceptual art reckoning with formalism\'s race-neutrality',
    pron: { written: 'ADD-uhm PEN-dull-tun', ipa: '/ˈædəm ˈpɛndəltən/', lang: 'en-US' },
    wiki: 'Adam_Pendleton',
  },

  // ── Drawing / Mixed ──
  a159: { // Marcel Dzama
    born: 'Winnipeg, Canada, 1974',
    based: 'Brooklyn, NY',
    training: 'University of Manitoba (BFA)',
    signature: 'Royal Art Lodge collective; root-beer-tinted drawings of bear-soldiers, ballerinas, and chess armies',
    method: 'Ink and root beer wash drawings + dioramas of a folk-cinematic world',
    thesis: 'Contemporary drawing can carry a coherent fictional cosmology as its primary mode',
    cohort: 'Royal Art Lodge (Winnipeg drawing collective, late 1990s–2008)',
    pron: { written: 'mar-SELL ZAH-mah', ipa: '/mɑrˈsɛl ˈzɑma/', lang: 'en-CA' },
    wiki: 'Marcel_Dzama',
  },
  a191: { // Raymond Pettibon
    born: 'Tucson, Arizona, 1957',
    based: 'New York',
    training: 'UCLA (economics) — no formal art training',
    signature: 'Black Flag flyers, SST and Minutemen album art; ink-and-text drawings',
    method: 'Pen-and-ink drawing braiding Henry James, William Blake, surf, baseball, and punk in flat graphic style',
    thesis: 'Text is a visual medium — the proper site of American literary thinking is the wall, not the novel',
    cohort: 'Younger brother of Black Flag\'s Greg Ginn; SoCal hardcore-punk graphic scene 1980s',
    pron: { written: 'PET-tih-bone', ipa: '/ˈpɛtəboʊn/', lang: 'en-US' },
    wiki: 'Raymond_Pettibon',
  },
  a735: { // Sophie Calle
    born: 'Paris, France, 1953',
    based: 'Paris, France',
    training: 'Self-directed; no formal art training',
    signature: 'Suite Vénitienne (1980); The Hotel (1981); Take Care of Yourself (2007); Exquisite Pain',
    method: 'Following strangers and contractual project-as-life works mixing surveillance and autobiography',
    thesis: 'The self is a public artifact — the rules under which we agree to be observed are the medium',
    cohort: 'French conceptual practice from late 1970s; French Pavilion Venice Biennale 2007',
    pron: { written: 'soh-FEE KAL', ipa: '/sɔˈfi kal/', lang: 'fr-FR' },
    wiki: 'Sophie_Calle',
  },
  a83: { // Glenn Ligon
    born: 'The Bronx, NY, 1960',
    based: 'New York',
    training: 'Wesleyan University; Whitney Independent Study Program',
    signature: 'Stranger in the Village; Untitled (I Am a Man); Warm Broad Glow neon',
    method: 'Text-based painting of phrases from Baldwin, Hurston, Pryor, and Civil Rights placards, degraded into illegibility',
    thesis: 'Race is legible not by sight but by language — painting can stage where the language stops working',
    cohort: 'Whitney ISP cohort; early-1990s identity-and-text painting',
    pron: { written: 'GLEN LYE-gun', ipa: '/ɡlɛn ˈlaɪɡən/', lang: 'en-US' },
    wiki: 'Glenn_Ligon',
  },

  // ── Batch 2 additions ──

  a596: { // Allora & Calzadilla
    born: 'Allora b. 1974 Philadelphia; Calzadilla b. 1971 Havana',
    based: 'San Juan, Puerto Rico',
    training: 'Allora: University of Richmond, MIT, Whitney ISP; Calzadilla: Bard College, Skowhegan',
    signature: 'Stop, Repair, Prepare (tuba-piano at MoMA); Land Mark; US Pavilion Venice Biennale 2011',
    method: 'Collaborative performance, sculpture, sound, and video staging geopolitics through bodies and instruments',
    thesis: 'Geopolitics enters art most precisely as sound and choreography — body of singer, soldier, animal',
    cohort: 'Working as a duo since 1995; politically engaged Puerto Rican practice',
    pron: { written: 'ah-LOR-uh & kal-zah-DEE-yah', ipa: '/əˈlɔrə ænd ˌkælzəˈdiːjə/', lang: 'es-PR' },
    wiki: 'Allora_and_Calzadilla',
  },
  a381: { // Mona Hatoum
    born: 'Beirut, Lebanon, 1952 (Palestinian family in exile)',
    based: 'London and Berlin',
    training: 'Byam Shaw School of Art and the Slade School of Fine Art, London',
    signature: 'Corps étranger (endoscope through her own body); Light Sentence; barbed-wire and metal-mesh furniture',
    method: 'Household objects scaled to weaponry; body-cavity video; rubber and steel domestic-as-prison installations',
    thesis: 'Exile is not a metaphor — it is a measurable property of a kitchen object',
    cohort: 'Stranded in London by the 1975 outbreak of the Lebanese Civil War; first generation of Arab diaspora artists in Britain',
    pron: { written: 'MOH-nah hah-TOOM', ipa: '/ˈmoʊna haˈtuːm/', lang: 'ar' },
    wiki: 'Mona_Hatoum',
  },
  a584: { // Rosemarie Trockel
    born: 'Schwerte, West Germany, 1952',
    based: 'Cologne, Germany',
    training: 'Werkkunstschule Köln',
    signature: 'Knitted-wool "paintings" with Playboy logos, hammer-and-sickles, and corporate marks',
    method: 'Industrial-machine-knitted wool canvases; ceramics; stovetop and book-draft assemblage',
    thesis: 'Femininity, taste, and category are themselves the material — refusing legibility is political labour',
    cohort: 'Emerged from the male-dominated 1980s German painting scene as a deliberate counter-figure',
    pron: { written: 'ROH-zuh-mah-ree TRO-kuhl', ipa: '/ˈʁoːzəmaʁiː ˈtʁɔkəl/', lang: 'de-DE' },
    wiki: 'Rosemarie_Trockel',
  },
  a533: { // Cyprien Gaillard
    born: 'Paris, France, 1980',
    based: 'Paris and Berlin',
    training: 'École Cantonale d\'Art de Lausanne (ECAL)',
    signature: 'Cities of Gold and Mirrors (Cancun); Nightlife (Cleveland); Ocean II Ocean — 35mm and 3D film',
    method: '35mm and stereoscopic 3D film of modernist ruin, ancient monument, and post-industrial decay',
    thesis: 'Contemporary destruction is too slow to be an event and too fast to be ruin — the camera finds the angle where time becomes visible',
    cohort: 'Post-2000s European video; works on modernist architecture\'s second life',
    pron: { written: 'see-pree-AHN guy-YAR', ipa: '/sipʁjɛ̃ ɡajaʁ/', lang: 'fr-FR' },
    wiki: 'Cyprien_Gaillard',
  },
  a821: { // Hans Op de Beeck
    born: 'Turnhout, Belgium, 1969',
    based: 'Brussels, Belgium',
    training: 'Sint-Lucas Beeldende Kunst, Antwerp; HISK, Ghent',
    signature: 'Sanctuary; The Collector\'s House — life-size grey monochrome interiors with grey figures',
    method: 'Sculpture, drawing, film, and installation rendered entirely in a single dust-grey palette',
    thesis: 'Grey is the contemporary condition\'s true colour — screen-flattened, decision-suspended, anaesthetised',
    cohort: 'Belgian-Flemish contemporary practice; HISK alumnus',
    pron: { written: 'HAHNS op deh BAKE', ipa: '/ɦɑns ɔp də beːk/', lang: 'nl-BE' },
    wiki: 'Hans_Op_de_Beeck',
  },
  a545: { // Karen Kilimnik
    born: 'Philadelphia, Pennsylvania, 1955',
    based: 'Philadelphia, Pennsylvania',
    training: 'Temple University, Tyler School of Art',
    signature: 'Small fan paintings of pop idols (Kate Moss, DiCaprio, ballet stars); ballet-stage and bedroom installations',
    method: 'Loose, fast painting in the hand of an obsessive teenage fan; immersive installation as set-design',
    thesis: 'Fan culture, romance, and femininity are serious painterly subjects — the polished MFA hand is one historical option among many',
    cohort: '1990s "scatter art" and the New York fan-painting moment',
    pron: { written: 'KIL-im-nick', ipa: '/ˈkɪlɪmnɪk/', lang: 'en-US' },
    wiki: 'Karen_Kilimnik',
  },
  a364: { // Mirosław Bałka
    born: 'Otwock, Poland, 1958',
    based: 'Otwock, Poland (Warsaw studio)',
    training: 'Academy of Fine Arts in Warsaw',
    signature: 'How It Is (Tate Modern Turbine Hall 2009, 30-metre dark steel box); soap-and-felt geometries; salt-and-steel floors',
    method: 'Sculpture dimensioned to the artist\'s own body or his Otwock childhood home, in centimetres',
    thesis: 'Sculpture\'s responsibility is to specific historical sites — the Polish-Jewish absence in the post-war landscape',
    cohort: 'Post-1989 Polish sculpture; Otwock\'s post-Holocaust geography',
    pron: { written: 'mee-ROH-swahf BAW-kah', ipa: '/miˈrɔswaf ˈbawka/', lang: 'pl-PL' },
    wiki: 'Miros%C5%82aw_Ba%C5%82ka',
  },
  a282: { // Maya Lin
    born: 'Athens, Ohio, 1959 (to Chinese parents arrived after 1949)',
    based: 'New York',
    training: 'Yale University (BA Architecture, MArch)',
    signature: 'Vietnam Veterans Memorial (1981, age 21); Wave Field; Pin River; Storm King\'s Wavefield',
    method: 'Earthworks, topographic and hydrographic translations into landscape sculpture and pin-and-glass installations',
    thesis: 'Landscape is the still-uncatalogued American memorial subject — the artist maps what is being lost while it is here',
    cohort: 'Architect-sculptor; Yale undergraduate who won the Vietnam memorial commission by competition at 21',
    pron: { written: 'MY-uh LIN', ipa: '/ˈmaɪə lɪn/', lang: 'en-US' },
    wiki: 'Maya_Lin',
  },
  a567: { // Pamela Rosenkranz
    born: 'Uri, Switzerland, 1979',
    based: 'Zürich, Switzerland',
    training: 'University of Bern; Università IUAV di Venezia (visual culture)',
    signature: 'Our Product (Swiss Pavilion Venice 2015 — pool of synthetic skin-tone liquid); Old Tree (NYC High Line)',
    method: 'Industrial colour, perfume, biotech materials, AI-generated avatars, engineered scented environments',
    thesis: 'The contemporary subject\'s body is already a corporate object — sculpture must work at the level of pigment, scent, serotonin',
    cohort: 'Post-internet Swiss conceptual sculpture; Venice Biennale Swiss Pavilion 2015',
    pron: { written: 'PAH-mel-ah ROH-zen-krants', ipa: '/ˈpaːmela ˈʁoːzn̩kʁants/', lang: 'de-CH' },
    wiki: 'Pamela_Rosenkranz',
  },
  a371: { // Cerith Wyn Evans
    born: 'Llanelli, Wales, 1958',
    based: 'London, UK',
    training: 'Saint Martin\'s School of Art; Royal College of Art',
    signature: 'Large flown neon-armature handwritten phrases; chandeliers flickering Morse-code transcripts',
    method: 'Neon, chandelier, optical glass, and Morse-code light routing literary texts through architecture',
    thesis: 'Light has a grammar — the work of art is a sentence the viewer has to finish',
    cohort: 'Began as a film-maker with Derek Jarman in the 1980s; shifted to sculpture and neon in the 1990s',
    pron: { written: 'KAIR-ith win EV-ans', ipa: '/ˈkɛrɪθ wɪn ˈɛvənz/', lang: 'cy' },
    wiki: 'Cerith_Wyn_Evans',
  },

  // ── Batch 3 (cycle 1 of automation) ──

  a270: { // Acaye Kerunen
    born: 'Uganda, 1979',
    based: 'Kampala and New York',
    training: 'Trained as an actor and curator; no formal art-school MFA',
    signature: 'Co-represented Uganda at the 2022 Venice Biennale (with Collin Sekajugo); Kwo (Life), Bende Wange',
    method: 'Hand-woven raffia, banana fibre, and palm leaf sculptures made with rural Ugandan women\'s craft cooperatives',
    thesis: 'Sculpture is a labour relation — the work is unfinished without the visible economy of who made it',
    cohort: 'Post-2018 African contemporary sculpture; first Ugandan pavilion at Venice in 2022',
    pron: { written: 'ah-CHAH-yeh keh-ROO-nen', ipa: '/əˈtʃɑːjə kəˈruːnən/', lang: 'en-UG' },
    wiki: 'Acaye_Kerunen',
  },
  a981: { // Agnes Scherer
    born: 'Lebach, Germany, 1985',
    based: 'Berlin and Salzburg',
    training: 'HBK Braunschweig',
    signature: 'The Salesman (2019); Cupid and the Animals (2021) — immersive operatic painted-set installations',
    method: 'Paints sets, writes libretti, builds puppets, and stages live performance inside a single gallery installation',
    thesis: 'The exhibition is a coherent theatrical event, not a display of discrete media objects',
    cohort: 'Contemporary German artist staging Gesamtkunstwerk against the atomised media categories of the art fair',
    pron: { written: 'AHG-ness SHEH-rer', ipa: '/ˈaɡnəs ˈʃeːʁɐ/', lang: 'de-DE' },
    wiki: 'Agnes_Scherer',
  },
  a815: { // Ahmed Mater
    born: 'Tabuk, Saudi Arabia, 1979',
    based: 'Abu Arish, Mecca, and London',
    training: 'King Khalid University (medicine); co-founded Edge of Arabia (2003)',
    signature: 'Desert of Pharan (2011–2016, Mecca redevelopment photography); Magnetism (2012, iron-filings around a magnet)',
    method: 'Photography, video, and installation documenting the construction-driven transformation of Islamic sacred space',
    thesis: 'The contemporary transformation of Mecca is a construction event, not a religious one',
    cohort: 'Saudi contemporary art post-2003; physician-artist generation in the Gulf',
    pron: { written: 'AH-med MAH-ter', ipa: '/ˈæhməd ˈmɑːtər/', lang: 'ar-SA' },
    wiki: 'Ahmed_Mater',
  },
  a784: { // Alejandro Campins
    born: 'Manzanillo, Cuba, 1981',
    based: 'Havana, Cuba',
    training: 'Instituto Superior de Arte (ISA), Havana',
    signature: 'Patria (2014), Lethargy (2013) — large canvases of abandoned modernist architecture and revolutionary monument',
    method: 'Atmospheric large-format landscape painting of Cuban modernist ruin',
    thesis: 'The Cuban revolutionary built environment is a romantic-sublime painting subject in the Constable sense',
    cohort: 'Contemporary Cuban painting trained at ISA; post-Special-Period generation',
    pron: { written: 'ah-leh-HAHN-droh KAHM-pinz', ipa: '/aleˈxandɾo ˈkampins/', lang: 'es-CU' },
    wiki: 'Alejandro_Campins',
  },
  a315: { // Alejandro Piñeiro Bello
    born: 'Pinar del Río, Cuba, 1990',
    based: 'Miami, Florida',
    training: 'Self-taught',
    signature: 'Tierra de Promisión (2022); Bahia Honda (2023) — Caribbean landscape and Afro-Cuban mythological hybridity',
    method: 'Large-scale figurative painting on cotton with mythological and tropical-landscape iconography',
    thesis: 'The Cuban-American imaginary is still being painted by people who left, into the present',
    cohort: 'Self-taught; explicit lineage from Wifredo Lam and José Bedia',
    pron: { written: 'ah-leh-HAHN-droh pee-NYEH-roh BEH-yo', ipa: '/aleˈxandɾo piˈɲeɾo ˈbeʎo/', lang: 'es-CU' },
    wiki: 'Alejandro_Pi%C3%B1eiro_Bello',
  },
  a946: { // Alex Da Corte
    born: 'Camden, New Jersey, 1980 (Venezuelan-Italian)',
    based: 'Philadelphia, Pennsylvania',
    training: 'University of the Arts (BFA); Yale University (MFA)',
    signature: 'Rubber Pencil Devil (2018); As Long as the Sun Lasts (Met rooftop commission, 2021)',
    method: 'Hyper-saturated video installation combining pop-culture, midcentury advertising, and stage-set sculpture',
    thesis: 'American consumer surrealism is a folk vernacular — take it seriously as form, not as celebration',
    cohort: 'Post-2010 American video installation; Met rooftop commission 2021',
    pron: { written: 'AL-ex dah-KOR-tay', ipa: '/ˈæleks dəˈkɔrteɪ/', lang: 'en-US' },
    wiki: 'Alex_Da_Corte',
  },
  a837: { // Ana Maria Tavares
    born: 'Belo Horizonte, Brazil, 1958',
    based: 'São Paulo, Brazil',
    training: 'Escola de Comunicações e Artes, Universidade de São Paulo',
    signature: 'Atlântico (2007); Desvios (2010) — mirror and steel installations of modernist transit space',
    method: 'Sculptural installations restaging airport, lobby, and Lúcio Costa transit-corridor materials',
    thesis: 'The seductive surfaces of Brazilian modernist transit space are the contemporary Brazilian sublime',
    cohort: 'Post-1980s Brazilian contemporary sculpture in the long shadow of Niemeyer and Costa',
    pron: { written: 'AH-nah mah-REE-ah tah-VAH-rehs', ipa: '/ˈɐnɐ mɐˈɾiɐ tɐˈvaɾɨs/', lang: 'pt-BR' },
    wiki: 'Ana_Maria_Tavares',
  },
  a591: { // Andrea Zittel
    born: 'Escondido, California, 1965',
    based: 'Joshua Tree, California (A-Z West)',
    training: 'San Diego State University (BFA); Rhode Island School of Design (MFA)',
    signature: 'A-Z Living Units (1994); A-Z Escape Vehicles (1996); A-Z Wagon Stations (2003); High Desert Test Sites',
    method: 'Tests experimental life-units (housing, clothing, food) personally; gallery is the brand catalogue',
    thesis: 'The structures of daily life — what you wear, sleep in, eat — are art\'s first and most consequential material',
    cohort: 'Post-1990s American socially engaged art; A-Z Enterprise founded 1991',
    pron: { written: 'AHN-dree-ah ZIT-uhl', ipa: '/ˈændriə ˈzɪtəl/', lang: 'en-US' },
    wiki: 'Andrea_Zittel',
  },
  a809: { // André Komatsu
    born: 'São Paulo, Brazil, 1978 (Japanese-Brazilian)',
    based: 'São Paulo, Brazil',
    training: 'Fundação Armando Álvares Penteado (FAAP), São Paulo',
    signature: 'Estado Provisório (2012); Reverso (2015) — precariously balanced construction-debris compositions',
    method: 'Sculpture from reinforcing bar, salvaged drywall, and construction debris of the São Paulo built environment',
    thesis: 'Latin American architectural power is most legible in its rubble; sculpture reads it without flattering it',
    cohort: 'Contemporary Brazilian sculpture; São Paulo brutalist-architecture lineage',
    pron: { written: 'ahn-DREH koh-MAH-tsoo', ipa: '/ɐ̃ˈdɾɛ koˈmatsu/', lang: 'pt-BR' },
    wiki: 'Andr%C3%A9_Komatsu',
  },
  a471: { // Annette Messager
    born: 'Berck-sur-Mer, France, 1943',
    based: 'Malakoff (Paris suburb), France',
    training: 'École nationale supérieure des Arts décoratifs, Paris',
    signature: 'Mes voeux (1989); Casino (Golden Lion, Venice 2005); Articulés-Désarticulés',
    method: 'Installations of stuffed animals, photographs, hand-written texts, and net-sewn body parts as unstable archive',
    thesis: 'The unfinished private archive is a feminist sculptural form the gallery cannot organise',
    cohort: 'Post-1968 French feminist art; central from the 1970s onward; Venice Golden Lion 2005',
    pron: { written: 'ah-NET meh-SAH-zhay', ipa: '/aˈnɛt mɛsaˈʒe/', lang: 'fr-FR' },
    wiki: 'Annette_Messager',
  },
  a904: { // Ariana Papademetropoulos
    born: 'Los Angeles, California, 1990',
    based: 'Los Angeles, California',
    training: 'California Institute of the Arts (CalArts)',
    signature: 'The Emerald Tablet (2022); photorealist canvases of decaying interiors with surreal apparitions',
    method: 'Oil photorealism of 1970s domestic interiors that bloom into mushrooms, portals, and fairytale apparitions',
    thesis: 'The American suburban interior is already a haunted hallucinogenic space — painting need only stop pretending otherwise',
    cohort: 'Contemporary Los Angeles painting in the post-Kilimnik fan-fairytale lineage',
    pron: { written: 'ah-ree-AH-nah pah-pah-deh-meh-TROH-poo-loss', ipa: '/ˌɑːriˈɑːnə ˌpɑːpədəmɪˈtrɒpəlɒs/', lang: 'en-US' },
    wiki: 'Ariana_Papademetropoulos',
  },
  a839: { // Armando Testa
    born: 'Turin, Italy, 1917 (d. 1992)',
    based: 'Turin, Italy',
    training: 'Scuola Tipografica Vigliardi-Paravia, Turin',
    signature: 'Punt e Mes campaign (1960); Papalla character (1968, for Philco); Pirelli and Lavazza identities',
    method: 'Graphic and advertising design collapsing Surrealist visual logic into mass commercial communication',
    thesis: 'The most legible Italian visual modernism of the 20th century is on billboards, not on canvas',
    cohort: 'Postwar Italian graphic design; founded Studio Armando Testa 1946',
    pron: { written: 'ar-MAHN-doh TEH-stah', ipa: '/arˈmando ˈtɛsta/', lang: 'it-IT' },
    wiki: 'Armando_Testa',
  },
  a927: { // Austyn Weiner
    born: 'Miami, Florida, 1989',
    based: 'Miami, Florida',
    training: 'Tulane University; Parsons School of Design',
    signature: 'Just Above My Head (2022); confessional-figurative-abstract canvases with scribbled text',
    method: 'Fast vibrating colour, scribbled text, and figurative passages layered at diaristic pitch',
    thesis: 'Post-internet female interiority is a serious painterly subject without sacrificing legibility',
    cohort: 'Late-2010s American women painters at the seam of abstraction and confessional figuration',
    pron: { written: 'AW-stin WHY-ner', ipa: '/ˈɔːstɪn ˈwaɪnər/', lang: 'en-US' },
    wiki: 'Austyn_Weiner',
  },
  a781: { // Barbana Bojadzi
    born: '1990',
    based: 'Balkans / Continua roster',
    training: 'No publicly documented art-school training',
    signature: 'Untitled paintings (2020 onward) — emerging Balkan domestic-memory practice',
    method: 'Painting and small-scale installation engaging memory, place, and family interior',
    thesis: 'What the contemporary attention economy cannot reward, painting can still hold',
    cohort: 'Continua\'s youngest-roster cohort; emerging Balkan contemporary practice',
    pron: { written: 'bar-BAH-nah BOH-yad-zee', ipa: '/barˈbana ˈbojadzi/', lang: 'mk-MK' },
    wiki: 'Barbana_Bojadzi',
  },
  a295: { // Beatriz Milhazes
    born: 'Rio de Janeiro, Brazil, 1960',
    based: 'Rio de Janeiro (Lapa neighbourhood studio)',
    training: 'Parque Lage School of Visual Arts, Rio de Janeiro',
    signature: 'Maresias (2002); Succulent Eggplants (1996) — decal-transferred floral abstractions',
    method: 'Layered decal-transfer painting that lifts plastic-mounted motifs onto canvas, then peels',
    thesis: 'Decoration, ornament, and the so-called feminine surface are abstraction\'s most under-read tradition',
    cohort: 'Brazilian contemporary painting; Carioca generation working from Parque Lage in the 1980s',
    pron: { written: 'beh-ah-TREES mil-YAH-zess', ipa: '/biaˈtɾis miˈʎazis/', lang: 'pt-BR' },
    wiki: 'Beatriz_Milhazes',
  },
  a890: { // Bertrand Lavier
    born: 'Châtillon-sur-Seine, France, 1949',
    based: 'Paris and Aignay-le-Duc, France',
    training: 'École nationale supérieure d\'horticulture, Versailles (horticulture, not art)',
    signature: 'Brandt/Haffner (1984); Walt Disney Productions series (1984 onward); overpainted appliance assemblages',
    method: 'Conceptual assemblage that overpaints, stacks, or welds together pairs of brand-name domestic objects',
    thesis: 'The readymade is a still-operative grammar; art-versus-commodity is governed by trademark law',
    cohort: 'Post-1970s French Conceptual art; figures de proue alongside Sophie Calle and Christian Boltanski',
    pron: { written: 'bair-TRAHN lah-vee-AY', ipa: '/bɛʁˈtʁɑ̃ laˈvje/', lang: 'fr-FR' },
    wiki: 'Bertrand_Lavier',
  },
  a979: { // Borna Sammak
    born: 'United States, 1985',
    based: 'New York',
    training: 'Tyler School of Art, Temple University',
    signature: 'Not Yet Titled (2014); Just Beachy (2018) — stock-footage and software-glitch composition',
    method: 'Video, painting, and digital collage from stock-footage libraries, screensavers, and Adobe artefacts',
    thesis: 'Commercial imagery is the only widely shared visual language — painting must take its glitches seriously',
    cohort: 'Post-internet American video and digital painting; mid-2010s New York scene',
    pron: { written: 'BOR-nah SAM-ahk', ipa: '/ˈbɔrnə ˈsæmæk/', lang: 'en-US' },
    wiki: 'Borna_Sammak',
  },
  a460: { // Brennan Gerard & Ryan Kelly
    born: 'Both b. 1978 (US)',
    based: 'New York and Los Angeles',
    training: 'Both: Whitney Independent Study Program; dance training before visual art',
    signature: 'Timelining (2014); Modern Living (2016, at Schindler & Eames houses); Lazarus (2022)',
    method: 'Live choreography of queer intimacy staged inside midcentury modernist houses; video documentation',
    thesis: 'The modernist house was always a stage; the duo restores the bodies its documentary photograph cropped out',
    cohort: 'Collaborative duo since 2003; Whitney ISP cohort; bridges dance and video art',
    pron: { written: 'GAIR-erd and KEL-ee', ipa: '/ˈɡɛrərd ænd ˈkɛli/', lang: 'en-US' },
    wiki: 'Gerard_%26_Kelly',
  },
  a911: { // Brian Rochefort
    born: 'Cranston, Rhode Island, 1985',
    based: 'Los Angeles, California',
    training: 'Rhode Island School of Design (BFA)',
    signature: 'Crater (vessel series, 2018 onward) — heavily encrusted multi-fired ceramic vessels',
    method: 'Vessels built up through dozens of glaze firings until the surface bubbles, encrusts, and slumps geologically',
    thesis: 'Ceramic is the only sculptural medium that visibly records every accident of its own making',
    cohort: 'Post-Voulkos contemporary American ceramicists working with deliberate ruin',
    pron: { written: 'BRY-an ROH-shuh-fort', ipa: '/ˈbraɪən ˈroʊʃəfɔrt/', lang: 'en-US' },
    wiki: 'Brian_Rochefort',
  },
  a845: { // Carla Accardi
    born: 'Trapani, Sicily, 1924 (d. 2014)',
    based: 'Rome, Italy',
    training: 'Academy of Fine Arts of Palermo; Academy of Fine Arts of Florence',
    signature: 'Co-founder of Forma 1 (1947); Tenda (1965); Sicofoil paintings on transparent industrial plastic',
    method: 'Sign-and-symbol abstract painting on transparent Sicofoil plastic rather than opaque canvas',
    thesis: 'Italian abstraction\'s most radical move was material — painting became transparent before painting was declared dead',
    cohort: 'Co-founder of Forma 1 (1947) with Pietro Consagra and Antonio Sanfilippo; Italian postwar abstraction',
    pron: { written: 'KAR-lah ah-KAR-dee', ipa: '/ˈkarla akˈkardi/', lang: 'it-IT' },
    wiki: 'Carla_Accardi',
  },
  a792: { // Carlos Cruz-Diez
    born: 'Caracas, Venezuela, 1923 (d. 2019)',
    based: 'Paris (from 1960) and Caracas',
    training: 'Escuela de Artes Plásticas y Aplicadas, Caracas',
    signature: 'Physichromie series (1959–2019); Chromosaturation (1965 onward) — kinetic colour rooms',
    method: 'Kinetic and Op art making colour autonomous from form, visible only when the viewer moves',
    thesis: 'Colour is not a property of objects but an event in time',
    cohort: 'Venezuelan kinetic art trio with Jesús Rafael Soto and Alejandro Otero',
    pron: { written: 'KAR-lohs KROOZ-dee-ess', ipa: '/ˈkarlos kɾusˈðjes/', lang: 'es-VE' },
    wiki: 'Carlos_Cruz-Diez',
  },
  a617: { // Carmen Herrera
    born: 'Havana, Cuba, 1915 (d. 2022)',
    based: 'New York (from 1939)',
    training: 'Studied architecture at the University of Havana; Art Students League, New York',
    signature: 'Blanco y Verde (1959); Iberic (1949) — hard-edge geometric abstraction',
    method: 'Two-colour hard-edge geometric abstraction, often shaped or diagonal canvases',
    thesis: 'The canon of geometric abstraction is wrong in its dates — the work was always there, the institutions chose not to look',
    cohort: 'Unrecognised for fifty years; first solo show at age 89 in 2004; estate-managed since 2022',
    pron: { written: 'KAR-men air-AIR-ah', ipa: '/ˈkaɾmen eˈreɾa/', lang: 'es-CU' },
    wiki: 'Carmen_Herrera',
  },
  a27: { // Carsten Höller
    born: 'Brussels, Belgium, 1961 (German nationality)',
    based: 'Stockholm, Sweden and Biriwa, Ghana',
    training: 'University of Kiel (PhD agricultural entomology — insect olfactory communication)',
    signature: 'Test Site (2006 Tate Modern Turbine Hall slides); Decision (2015); Mushroom Suite (2000 onward)',
    method: 'Gallery-as-laboratory installations using slides, hallucinogenic mushrooms, and mirror-cube perceptual environments',
    thesis: 'Art\'s claim on perception is empirical — uncertainty is the experience, not a defect of it',
    cohort: 'Trained scientist turned artist; post-1990 relational and perceptual art',
    pron: { written: 'KAR-sten HUR-luhr', ipa: '/ˈkaʁstn̩ ˈhœlɐ/', lang: 'de-DE' },
    wiki: 'Carsten_H%C3%B6ller',
  },
  a425: { // Cecile Abish
    born: 'New York, NY, 1931 (d. 2023)',
    based: 'New York (with periods in Cologne)',
    training: 'Hunter College; later associations with the NYC post-minimal scene',
    signature: '4 Into 3 (1973); Equal Quantities (1975); Crossings (1978) — ephemeral floor-based installations',
    method: 'Sand, gravel, plywood, and tape grids laid on gallery floors as temporary configurations, documented photographically',
    thesis: 'Sculpture\'s permanence is a curatorial assumption — the photograph is the work\'s primary site',
    cohort: 'Post-minimal and process-art generation; married to writer Walter Abish',
    pron: { written: 'seh-SEEL AY-bish', ipa: '/səˈsiːl ˈeɪbɪʃ/', lang: 'en-US' },
    wiki: 'Cecile_Abish',
  },
  a439: { // Christian Boltanski
    born: 'Paris, France, 1944 (day of city\'s liberation; d. 2021)',
    based: 'Malakoff (Paris suburb), France',
    training: 'Self-taught (no formal art education)',
    signature: 'Personnes (Paris Monumenta 2010); The Reserves (1989); the Inventory of the Children of Dijon',
    method: 'Civic-scale installations of clothing, photographs, recorded heartbeats, and printed names',
    thesis: 'Sculpture\'s responsibility is to count the dead one by one — even when no name remains',
    cohort: 'Post-WWII French Jewish memory; father hidden under floorboards during the Occupation',
    pron: { written: 'krees-tee-AHN bol-TAHN-skee', ipa: '/kʁistjɑ̃ bɔlˈtɑ̃ski/', lang: 'fr-FR' },
    wiki: 'Christian_Boltanski',
  },
  a881: { // Christian Holstad
    born: 'Long Island, NY, 1972',
    based: 'Brooklyn, NY',
    training: 'Pratt Institute',
    signature: 'Newspaper Erasure Drawings (2005 onward) — front pages of the NY Times rubbed out by hand',
    method: 'Erasure drawing on newsprint; sculpture, textile, and ephemeral performance in queer-archival register',
    thesis: 'The daily newspaper is a queer archive in disguise — erasure can be a reading practice',
    cohort: 'Early-2000s queer drawing-and-textile generation in New York',
    pron: { written: 'KRIS-chen HOHL-stad', ipa: '/ˈkrɪstʃən ˈhoʊlstæd/', lang: 'en-US' },
    wiki: 'Christian_Holstad',
  },
  a984: { // Christiana Soulou
    born: 'Athens, Greece, 1961',
    based: 'Athens, Greece',
    training: 'Athens School of Fine Arts',
    signature: 'Characters of Balzac (2012); Animal Kingdom (2015)',
    method: 'Pencil and coloured-pencil drawing of literary and zoological subjects in slow precise line',
    thesis: 'Drawing is a reading medium — a character can be drawn only by someone who read the novel slowly',
    cohort: 'Contemporary Greek drawing tradition linking modernism to medieval manuscript',
    pron: { written: 'krees-tee-AH-nah SOO-loo', ipa: '/xɾistiˈana ˈsulu/', lang: 'el-GR' },
    wiki: 'Christiana_Soulou',
  },
  a218: { // Christopher Williams
    born: 'Los Angeles, California, 1956',
    based: 'Los Angeles, California',
    training: 'California Institute of the Arts (CalArts) under John Baldessari',
    signature: 'Angola to Vietnam* (1989); For Example (2003 onward) — meticulously staged conceptual photography',
    method: 'Strict conceptual photography re-staging commercial product, industrial-catalogue, and Cold War darkroom protocols',
    thesis: 'The conventions of photography are the subject — the obedient image is the most political one',
    cohort: 'CalArts conceptual photography lineage from Baldessari; mid-1980s onward',
    pron: { written: 'KRIS-tuh-fer WIL-yams', ipa: '/ˈkrɪstəfər ˈwɪljəmz/', lang: 'en-US' },
    wiki: 'Christopher_Williams_(artist)',
  },
  a957: { // Dada Khanyisa
    born: 'Mthatha, South Africa, 1991',
    based: 'Cape Town and Johannesburg',
    training: 'Michaelis School of Fine Art, University of Cape Town',
    signature: 'Good Feelings (2020); Moments of Joy (2021) — carved-and-painted wood reliefs of Black queer social life',
    method: 'Wall-mounted reliefs combining carved-and-painted wood with mixed-media collage',
    thesis: 'Black queer joy is itself a sufficient and political painterly subject',
    cohort: 'Post-apartheid South African painting; post-Marlene-Dumas Michaelis generation',
    pron: { written: 'DAH-dah kahn-YEE-sah', ipa: '/ˈdaːda kʰaˈɲisa/', lang: 'xh' },
    wiki: 'Dada_Khanyisa',
  },
  a284: { // Damian Loeb
    born: 'New Haven, Connecticut, 1970',
    based: 'New York',
    training: 'Self-taught',
    signature: 'Sora (2009); Lunaris (2014) — cinematic photorealist canvases of film, photography, astronomy',
    method: 'Hyperreal oil painting from film stills, satellite imagery, and astronomical photographs',
    thesis: 'Photorealism\'s contemporary job is to imitate the screen — and the painting must know which screen',
    cohort: 'Late-1990s American photorealist painters (with Currin, Yuskavage, Peyton)',
    pron: { written: 'DAY-mee-uhn LOHB', ipa: '/ˈdeɪmiən loʊb/', lang: 'en-US' },
    wiki: 'Damian_Loeb',
  },
  a602: { // Daniel Buren
    born: 'Boulogne-Billancourt, France, 1938',
    based: 'Paris, France',
    training: 'École nationale supérieure des métiers d\'art, Paris',
    signature: 'Les Deux Plateaux (1985–86, Palais Royal columns); Excentrique(s) (Grand Palais 2012); Photo-souvenirs',
    method: 'Since 1965, sole material is 8.7-cm alternating-stripe in-situ work deployed across architectural sites',
    thesis: 'The stripe is not a style but a tool — a visible instrument by which any site reveals its politics',
    cohort: 'Co-founder of BMPT (1966) with Olivier Mosset, Michel Parmentier, and Niele Toroni',
    pron: { written: 'dahn-YEL boo-REHN', ipa: '/danjɛl byʁɛ̃/', lang: 'fr-FR' },
    wiki: 'Daniel_Buren',
  },
  a958: { // David Korty
    born: 'San Francisco, California, 1971',
    based: 'Los Angeles, California',
    training: 'UCLA (BA); California College of the Arts (MFA)',
    signature: 'Blue Figure (2017); Yellow Grid (2019) — mixed-media painting integrating print and gesture',
    method: 'Collaged mixed-media on paper and canvas combining silkscreen, print, and delicate painterly mark',
    thesis: 'The LA atmospheric register holds observational drawing and abstraction at once',
    cohort: 'Early-2000s West Coast painters between watercolour landscape and post-pop abstraction',
    pron: { written: 'DAY-vid KOR-tee', ipa: '/ˈdeɪvɪd ˈkɔrti/', lang: 'en-US' },
    wiki: 'David_Korty',
  },
  a886: { // Dennis Kardon
    born: 'Des Moines, Iowa, 1950',
    based: 'New York',
    training: 'Yale University (BA, MFA)',
    signature: 'Jewish Noses (1993) — installation of 54 oil-painted ceramic noses of friends and acquaintances',
    method: 'Figurative painting that also turns phenotypic stereotype back on itself as material evidence',
    thesis: 'Figuration\'s contract is governed by perception\'s social conditioning — the painter is no neutral observer',
    cohort: 'Painter-and-critic figure; Yale-trained figurative generation of the 1980s',
    pron: { written: 'KAR-dun', ipa: '/ˈkɑrdən/', lang: 'en-US' },
    wiki: 'Dennis_Kardon',
  },
  a864: { // Diane Dal-Pra
    born: 'Bordeaux, France, 1991',
    based: 'Paris, France',
    training: 'École nationale supérieure des Beaux-Arts, Paris',
    signature: 'Devotional Objects (2022) — small slow figurative still-life and domestic-gesture painting',
    method: 'Muted brown-grey oil painting of women\'s hands, ritual gesture, textile, and ceramics',
    thesis: 'Domestic ritual is still under-painted; still life and genre scene remain serious territory for women\'s painting',
    cohort: 'Late-2010s French young women painters at the seam of Dutch genre and editorial photography',
    pron: { written: 'dee-AHN dal-PRAH', ipa: '/djan dalˈpʁa/', lang: 'fr-FR' },
    wiki: 'Diane_Dal-Pra',
  },
  a968: { // Diego Marcon
    born: 'Busto Arsizio, Italy, 1985',
    based: 'Milan, Italy',
    training: 'Accademia di Belle Arti di Brera, Milan',
    signature: 'Ludwig (2018); The Parents\' Room (2021) — short films with prosthetic-faced actors and looping music',
    method: 'Meticulously crafted short film combining live actors, prosthetics, CGI, and loop structure',
    thesis: 'The loop, not the narrative arc, is the contemporary form for cinematic dread and pathos',
    cohort: 'Contemporary Italian short-film art; gallery cinema circuit',
    pron: { written: 'dee-EH-go MAR-kon', ipa: '/ˈdjɛɡo ˈmarkon/', lang: 'it-IT' },
    wiki: 'Diego_Marcon',
  },
  a868: { // Dominique Fung
    born: 'Ottawa, Canada, 1987 (Hong Kong Chinese descent)',
    based: 'Brooklyn, NY',
    training: 'Capilano College, North Vancouver',
    signature: 'It\'s Not Polite to Stare (2021) — Asian women, museum vitrines, antiquities, and orientalist interiors',
    method: 'Lush figurative painting of Asian women, museum vitrines, antiquities in the European orientalist tradition',
    thesis: 'The Asian female body has been Western painting\'s decorative subject for three centuries — refuse to flinch',
    cohort: 'Post-2015 Asian diaspora painters reckoning with the museum\'s catalogue',
    pron: { written: 'doh-mee-NEEK FUNG', ipa: '/dɒmɪˈniːk fʌŋ/', lang: 'en-CA' },
    wiki: 'Dominique_Fung',
  },
  a889: { // Elad Lassry
    born: 'Tel Aviv, Israel, 1977',
    based: 'Los Angeles, California',
    training: 'University of Southern California (MFA); California Institute of the Arts (BFA)',
    signature: 'Untitled (Red Cabbage) (2009); custom-framed editorial-still photographs as discrete objects',
    method: 'Commercial-still photography in custom-coloured frames physically continuous with the image',
    thesis: 'The photographic object\'s frame is part of the image; contemporary photography\'s subject is its own display',
    cohort: 'Post-2007 Los Angeles photographers working at the seam of editorial and conceptual',
    pron: { written: 'eh-LAHD LAH-sree', ipa: '/eˈlad ˈlasri/', lang: 'he-IL' },
    wiki: 'Elad_Lassry',
  },
  a788: { // Elizabet Cerviño
    born: 'Manzanillo, Cuba, 1986',
    based: 'Havana and Madrid',
    training: 'Instituto Superior de Arte (ISA), Havana',
    signature: 'Llanto (2014); Marabú (2016) — elemental sculpture and painting with earth, sea-salt, wax',
    method: 'Sculpture and installation with earth, sea-salt, candle-wax, plant material, and the artist\'s own body',
    thesis: 'The post-revolutionary Cuban artist\'s most reliable subject is the elements themselves',
    cohort: 'Contemporary Cuban sculpture rooted in Caribbean Catholicism and Yoruba ritual',
    pron: { written: 'eh-lee-sah-BET sair-VEE-nyo', ipa: '/elisaˈβet seɾˈβiɲo/', lang: 'es-CU' },
    wiki: 'Elizabet_Cervi%C3%B1o',
  },
  a180: { // Emma McIntyre
    born: 'Auckland, New Zealand, 1990',
    based: 'Los Angeles, California',
    training: 'Elam School of Fine Arts, Auckland (BFA); ArtCenter College of Design (MFA)',
    signature: 'Rose in a glass (2023); A Wild Note of Longing (2023) — gestural oxidation-and-pour abstraction',
    method: 'Saturated colour built through oxidation, stain, and pour rather than hard-edge',
    thesis: 'The chromatic, atmospheric lyric problem of mid-century women painters is still unfinished',
    cohort: 'Late-2010s LA abstract painters in the Frankenthaler-Steir lineage',
    pron: { written: 'EM-uh mac-IN-tyre', ipa: '/ˈɛmə ˌmækɪnˈtaɪər/', lang: 'en-NZ' },
    wiki: 'Emma_McIntyre',
  },
  a254: { // Emmet Gowin
    born: 'Danville, Virginia, 1941',
    based: 'Newtown, Pennsylvania',
    training: 'Richmond Professional Institute (BFA); Rhode Island School of Design (MFA, under Harry Callahan)',
    signature: 'Edith, Danville, Virginia (1971); aerial photographs of US nuclear test sites (1996)',
    method: 'Intimate large-format family portraiture (1969 onward); aerial photography of altered landscapes (post-1980)',
    thesis: 'The photographer\'s responsibility extends to the kitchen table and to the cratered Earth — held at the same level of care',
    cohort: 'Taught at Princeton 1973–2009; student of Harry Callahan',
    pron: { written: 'EM-it GOH-win', ipa: '/ˈɛmət ˈɡoʊɪn/', lang: 'en-US' },
    wiki: 'Emmet_Gowin',
  },
  a437: { // Eric Orr
    born: 'Covington, Kentucky, 1939 (d. 1998)',
    based: 'Los Angeles, California',
    training: 'University of Cincinnati; informal LA Light and Space milieu',
    signature: 'Zero Mass (1972); Sunrise (1985); Prime Matter (1989) — immersive Light and Space environments',
    method: 'Immersive rooms using fire, water, blood, lead, and gold leaf for elemental perceptual experience',
    thesis: 'California perception art was never a single Turrell school — the elemental-alchemical strand is under-credited',
    cohort: 'Los Angeles Light and Space alongside Robert Irwin, James Turrell, Doug Wheeler',
    pron: { written: 'ER-ic OHR', ipa: '/ˈɛrɪk ɔr/', lang: 'en-US' },
    wiki: 'Eric_Orr_(artist)',
  },
  a732: { // Erwin Wurm
    born: 'Bruck an der Mur, Austria, 1954',
    based: 'Vienna and Limberg, Austria',
    training: 'Mozarteum, Salzburg; Academy of Applied Arts, Vienna; Academy of Fine Arts, Vienna',
    signature: 'One Minute Sculptures (1996 onward); Fat Car (2001); Fat House (2003)',
    method: 'Instruction-based body sculpture (One Minute) and physically swollen consumer goods (Fat series)',
    thesis: 'Sculpture\'s medium in the post-industrial age is the body\'s relation to commodity',
    cohort: 'Austrian contemporary sculpture; long-time professor at Universität für angewandte Kunst Wien',
    pron: { written: 'AIR-vin VOORM', ipa: '/ˈɛʁvin vʊʁm/', lang: 'de-AT' },
    wiki: 'Erwin_Wurm',
  },
  a915: { // Ferrari Sheppard
    born: 'Chicago, Illinois, 1983',
    based: 'Los Angeles, California',
    training: 'Largely self-taught; prior career in political journalism',
    signature: 'In My Mind (2021); gestural mixed-media Black-figurative painting with charcoal, gold leaf, acrylic',
    method: 'Charcoal-drawn Black figures with gold-leaf passages and gestural acrylic on raw linen',
    thesis: 'African American figurative painting can claim explicitly devotional gravitas — gold leaf as contemporary, not nostalgic',
    cohort: 'Post-Kerry James Marshall figurative generation; journalist-turned-painter',
    pron: { written: 'fuh-RAH-ree SHEP-erd', ipa: '/fəˈrɑːri ˈʃɛpərd/', lang: 'en-US' },
    wiki: 'Ferrari_Sheppard',
  },
  a897: { // France-Lise McGurn
    born: 'Glasgow, Scotland, 1983',
    based: 'Glasgow, Scotland',
    training: 'Glasgow School of Art (BA); Royal College of Art, London (MA)',
    signature: 'Sleepless (2019) — wall-and-floor extending figurative painting of nightlife and women',
    method: 'Fluid contour-line painting that extends beyond the canvas onto gallery walls and floors',
    thesis: 'The wall painting — fresco\'s contemporary descendant — is a feminist sculptural format',
    cohort: 'Post-2010 Glasgow contemporary painting; Glasgow School of Art lineage',
    pron: { written: 'FRAHNS-leez muh-GURN', ipa: '/ˈfrɑːnsliːz məˈɡɜrn/', lang: 'en-GB' },
    wiki: 'France-Lise_McGurn',
  },
  a959: { // Gabriel Kuri
    born: 'Mexico City, Mexico, 1970',
    based: 'Brussels, Belgium and Los Angeles, California',
    training: 'Universidad Iberoamericana, Mexico City; Goldsmiths, London',
    signature: 'Donation Box (2010); Spent (2014); receipts-and-marble assemblage sculpture',
    method: 'Combines receipts, cigarette butts, marble, and concrete in arrangements diagramming economic micro-transactions',
    thesis: 'Sculpture\'s subject in late capitalism is the receipt — the smallest, most truthful record of how an economy behaves',
    cohort: 'Mexico City taller around Gabriel Orozco in the 1990s; emerged with Bonillas, Eredia, Reyes',
    pron: { written: 'GAH-bree-el KOO-ree', ipa: '/ɡaˈβɾjel ˈkuɾi/', lang: 'es-MX' },
    wiki: 'Gabriel_Kuri',
  },
  a873: { // Gelitin
    born: 'Founded Vienna 1993 (Ali Janka, Wolfgang Gantner, Florian Reither, Tobias Urban)',
    based: 'Vienna, Austria',
    training: 'Met as adolescents at a Catholic summer camp; mostly self-organised',
    signature: 'The B-Thing (2000 World Trade Center balcony intervention); Hase (2005, 200-foot pink stuffed rabbit on Italian hillside)',
    method: 'Large-scale absurd public interventions and performances, often body-based and physically risky',
    thesis: 'Contemporary sculpture\'s residual seriousness is the problem — the collective drunk exhibitionist body is the only honest material',
    cohort: 'Austrian collaborative formed 1993; key works at Venice Biennale, P.S.1, Centre Pompidou',
    pron: { written: 'GEL-uh-tin', ipa: '/ˈɡɛlətɪn/', lang: 'de-AT' },
    wiki: 'Gelitin',
  },

  // ── Chunk 2 ──

  a953: { // Georg Herold
    born: 'Jena, East Germany, 1947',
    based: 'Cologne, Germany',
    training: 'Hochschule für bildende Künste Hamburg, under Sigmar Polke',
    signature: 'Latte Figures (roof-batten human-sized figures, 2000s); Caviar Paintings (1989)',
    method: 'Absurd low-grade materials — roof battens, bricks, caviar, potato — assembled into figures that mock heroic German sculpture',
    thesis: 'Cultural value is a joke history plays on its materials; the sculptor who pretends otherwise is in on the lie',
    cohort: '1980s German neo-avant-garde Cologne scene; escaped East Germany via Czechoslovakia in the 1970s',
    pron: { written: 'GAY-org HEH-rold', ipa: '/ˈɡeːɔʁk ˈheːʁɔlt/', lang: 'de-DE' },
    wiki: 'Georg_Herold',
  },
  a951: { // Georgia Gardner Gray
    born: 'Washington, DC, 1988',
    based: 'Berlin, Germany',
    training: 'Cooper Union (BFA); Städelschule, Frankfurt (under Amy Sillman)',
    signature: 'Commuters (2018); Terrace (2020) — figurative paintings of contemporary Western social tableaux',
    method: 'Figurative oil painting staged with the theatricality of a set and the cruelty of a satirist',
    thesis: 'The contemporary group portrait can render social humiliation as precisely as classical painting rendered grace',
    cohort: 'Post-2015 Berlin painters out of the Städelschule under Sillman',
    pron: { written: 'JOR-jah GARD-ner GRAY', ipa: '/ˈdʒɔrdʒə ˈɡɑrdnər ɡreɪ/', lang: 'en-US' },
    wiki: 'Georgia_Gardner_Gray',
  },
  a876: { // Giorgio Griffa
    born: 'Turin, Italy, 1936',
    based: 'Turin, Italy',
    training: 'Trained as a lawyer (no art-school MFA); painting practice from the late 1960s',
    signature: 'Segni orizzontali (1975); Canone aureo (2010) — repeated marks on unstretched raw canvas',
    method: 'Repeated mark — dashes, horizontals, ideograms — on raw unstretched canvas that stops when the canvas is no longer curious about itself',
    thesis: 'Painting is a practice of attention, not production — the unfinished canvas, folded when not shown, is the truer object',
    cohort: 'Loosely associated with Arte Povera and Italian analytical painting; Turin scene from the late 1960s',
    pron: { written: 'JOR-joh GRIFF-ah', ipa: '/ˈdʒɔrdʒo ˈɡriffa/', lang: 'it-IT' },
    wiki: 'Giorgio_Griffa',
  },
  a859: { // Giulia Cenci
    born: 'Cortona, Italy, 1988',
    based: 'Cortona, Italy and Amsterdam',
    training: 'Brera Academy, Milan; Rijksakademie van beeldende kunsten, Amsterdam',
    signature: 'dry salvages (2022); secondary forest (2021) — landscape-scale aluminium and animal-mold installations',
    method: 'Cast aluminium, industrial detritus, and animal-derived molds assembled into hybrid creature-forms at landscape scale',
    thesis: 'Sculpture\'s true subject is the agricultural-industrial ruin of Italy\'s countryside — the human figure is no longer its most legible body',
    cohort: 'Post-2015 Italian sculpture out of the Rijksakademie; emerged with Quirine Racké and Marwa Arsanios',
    pron: { written: 'JOO-lee-ah CHEN-chee', ipa: '/ˈdʒulja ˈtʃɛntʃi/', lang: 'it-IT' },
    wiki: 'Giulia_Cenci',
  },
  a268: { // Glenn Kaino
    born: 'Los Angeles, California, 1972',
    based: 'Los Angeles, California',
    training: 'UC Irvine (BA); UC San Diego (MFA)',
    signature: 'Bridge (2014, with Tommie Smith — 200 gold-plated cast arms); In the Light of a Shadow (2021, Mass MoCA, Bloody Sunday bullets cast as chandelier)',
    method: 'Conceptual sculpture and installation in explicit collaboration with named civic actors and historical witnesses',
    thesis: 'Political memory needs material vessels at the right scale — sculpture\'s job is to be the steady collaborator',
    cohort: 'Post-2000 Los Angeles conceptual sculpture; collaborations with Tommie Smith, Bryan Stevenson, and the Equal Justice Initiative',
    pron: { written: 'GLEN KAY-noh', ipa: '/ɡlɛn ˈkeɪnoʊ/', lang: 'en-US' },
    wiki: 'Glenn_Kaino',
  },
  a799: { // Gu Dexin
    born: 'Beijing, China, 1962',
    based: 'Beijing (retired from art 2009)',
    training: 'Largely self-taught',
    signature: 'Plastic Pieces (1983–89, melted plastic); 2009-05-02 (2009, his final work — the date he stopped making art)',
    method: 'Installation of rotting fruit, melted plastic, raw meat, and pressed flesh — materials that refused permanence',
    thesis: 'The artist\'s most powerful gesture can be to stop — May 2, 2009 was his last work and he has made nothing since',
    cohort: 'Foundational figure of the 1985 New Wave Chinese avant-garde alongside Huang Yong Ping and Xu Bing',
    pron: { written: 'GOO DEH-shin', ipa: '/ku tɤ̌ɕín/', lang: 'zh-CN' },
    wiki: 'Gu_Dexin',
  },
  a869: { // Günther Förg
    born: 'Füssen, Germany, 1952 (d. 2013)',
    based: 'Munich and Areuse, Switzerland',
    training: 'Akademie der Bildenden Künste München under Karl Fred Dahmen',
    signature: 'Grey Paintings (1973 onward); Spot Paintings (2007); lead-and-aluminium wall works; photographs of fascist-era Italian architecture',
    method: 'Deliberately uneven, almost careless gestural abstraction collapsing the language of postwar modernist painting',
    thesis: 'European modernist abstraction is a found language — usable, exhaustible, and worth refusing to perfect',
    cohort: 'Postwar German painting after Polke, Richter, and Kiefer; Munich Academy lineage',
    pron: { written: 'GUYN-tuhr FURG', ipa: '/ˈɡʏntɐ fœʁk/', lang: 'de-DE' },
    wiki: 'G%C3%BCnther_F%C3%B6rg',
  },
  a230: { // Harry Callahan
    born: 'Detroit, Michigan, 1912 (d. 1999)',
    based: 'Atlanta, Georgia (late career); Providence, Rhode Island (RISD)',
    training: 'Self-taught (1938 onward); hired by Moholy-Nagy at the Institute of Design, Chicago, 1946',
    signature: 'Eleanor series (1947–60, photographs of his wife); Chicago (1950); Cape Cod (1972)',
    method: 'Black-and-white photography returning across decades to a few intimate and natural subjects',
    thesis: 'Photography\'s discipline is attention, not novelty — the same subject, returned to over decades, is the longest education',
    cohort: 'Institute of Design Chicago (after Moholy-Nagy); head of photography at RISD; taught Emmet Gowin',
    pron: { written: 'HAIR-ee KAL-uh-han', ipa: '/ˈhæri ˈkæləhæn/', lang: 'en-US' },
    wiki: 'Harry_Callahan_(photographer)',
  },
  a856: { // Hejum Bä
    born: 'South Korea, 1987',
    based: 'Seoul / international',
    training: 'Seoul National University',
    signature: 'Untitled (2022) abstract canvases working at the seam of East Asian calligraphic line and Western post-painterly abstraction',
    method: 'Abstract painting investigating line, gesture, and the body\'s relationship to the canvas surface',
    thesis: 'The line — drawn, painted, breathed onto a surface — is painting\'s most under-credited unit',
    cohort: 'Contemporary Korean abstract painters working in international gallery circuit',
    pron: { written: 'HEH-juhm BAE', ipa: '/hed͡ʑum pɛ/', lang: 'ko-KR' },
    wiki: 'Hejum_B%C3%A4',
  },
  a969: { // Helen Marten
    born: 'Macclesfield, England, 1985',
    based: 'London, UK',
    training: 'Central Saint Martins; Ruskin School of Art, Oxford',
    signature: 'Lunar Nibs (2016); Eucalyptus, Let Us In (2016) — won Turner Prize and inaugural Hepworth Prize the same year',
    method: 'Dense hybrid installations combining welded steel, ceramic, screen-printed textile, found object, and dense written text',
    thesis: 'Sculpture\'s task is to overwhelm the viewer\'s pattern-matching ability — to be more dense than the museum label can be',
    cohort: '2010s British sculpture; Turner Prize and Hepworth Sculpture Prize both 2016',
    pron: { written: 'HEL-en MAR-ten', ipa: '/ˈhɛlən ˈmɑrtən/', lang: 'en-GB' },
    wiki: 'Helen_Marten',
  },

  // portrait field is populated post-fetch
};

if (typeof window !== 'undefined') window.QUIZ_FACTS = QUIZ_FACTS;
